### ISSUE TITLE
加强引导与说明

### ISSUE THREAD

**Issue by Jiaxin-Wen** [xwwwwww/storyboard#1]
针对用户调研中出现多次的意见，加强网站的引导与说明。

> - 引导不够，只看网站不知道看啥
> - 推荐写个使用说明，不然有的功能我找半天
> - 一开始不知道要干啥 

具体措施

- 实现新手引导功能
- 可以额外增加一个说明页，介绍网站，给个github的链接。

**Comment by 111116** [comment]
http://storyboards.cc/help/
