### ISSUE TITLE
完善提示

### ISSUE THREAD

**Issue by Jiaxin-Wen** [xwwwwww/storyboard#2]
针对用户调研中出现的如下意见，完善网站的提示。
> - 邮箱格式错误，显示”未知的错误“
> - 帮写功能的敏感词提示要更全面，不然用户不知道bad input text的含义，也不知道如何修改。

- 后端接口在返回时大多都具有msg字段，针对不同status code有相应调整。前端可以利用好msg字段。
- 敏感词的问题需要再思考一下
   - 由于敏感词的词表比较大，完全禁止用户输入敏感词可能会影响体验。
   - 是否要提示用户哪些词是敏感词
   - 可以考虑在输入到模型前把敏感词全都过滤掉，但这可能导致一部分关键字的损失。

**Comment by 111116** [comment]
前端TODO：token失效时做任何操作401都给出提示

**Comment by Jiaxin-Wen** [comment]
敏感词过滤已完成。

**Comment by 111116** [comment]
Done
