### ISSUE TITLE
关于【生成文本】信息的维护和显示

### ISSUE THREAD

**Issue by Jiaxin-Wen** [xwwwwww/storyboard#4]
motivation主要是让用户能更直观的感受到”智能“。

如何做是一个问题。
感觉直接highlight机器生成的字段可能会不美观，影响阅读体验。
可以有一个button选择是否切换？
或者给一个统计信息，本文有x%的文字是生成的？
或是网站累计使用帮写功能x次之类？

**Comment by 111116** [comment]
done
